name: Build Backend Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ secrets.GHCR_USERNAME }}/minichatgpt-backend

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/minichatgpt-backend:latest
            ghcr.io/${{ secrets.GHCR_USERNAME }}/minichatgpt-backend:${{ github.sha }}